<?php

namespace Container1Jl56aO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionStartService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the private 'Glpi\Kernel\Listener\PostBootListener\SessionStart' shared autowired service.
     *
     * @return \Glpi\Kernel\Listener\PostBootListener\SessionStart
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Kernel'.\DIRECTORY_SEPARATOR.'Listener'.\DIRECTORY_SEPARATOR.'PostBootListener'.\DIRECTORY_SEPARATOR.'SessionStart.php';

        return $container->privates['Glpi\\Kernel\\Listener\\PostBootListener\\SessionStart'] = new \Glpi\Kernel\Listener\PostBootListener\SessionStart(($container->privates['Glpi\\Http\\SessionManager'] ??= new \Glpi\Http\SessionManager()), \dirname(__DIR__, 5));
    }
}
