<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerARvYx1q\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerARvYx1q/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerARvYx1q.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerARvYx1q\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerARvYx1q\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'ARvYx1q',
    'container.build_id' => '8790003e',
    'container.build_time' => 1783867524,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerARvYx1q');
