<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1xQR4xk\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1xQR4xk/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/Container1xQR4xk.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\Container1xQR4xk\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \Container1xQR4xk\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => '1xQR4xk',
    'container.build_id' => 'ebacfa8b',
    'container.build_time' => 1783939922,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1xQR4xk');
