<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3XmqeMx\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3XmqeMx/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/Container3XmqeMx.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\Container3XmqeMx\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \Container3XmqeMx\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => '3XmqeMx',
    'container.build_id' => '87d84881',
    'container.build_time' => 1784362251,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3XmqeMx');
