<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOgLt8VI\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOgLt8VI/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerOgLt8VI.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerOgLt8VI\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \ContainerOgLt8VI\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => 'OgLt8VI',
    'container.build_id' => '0a069229',
    'container.build_time' => 1784303578,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOgLt8VI');
