<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8Dr7sa8\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8Dr7sa8/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/Container8Dr7sa8.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\Container8Dr7sa8\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \Container8Dr7sa8\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => '8Dr7sa8',
    'container.build_id' => '1222545d',
    'container.build_time' => 1784050103,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8Dr7sa8');
