<?php

namespace Container8Dr7sa8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\InstallController' shared autowired service.
     *
     * @return \Glpi\Controller\InstallController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'PublicService.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'AsyncOperationProgressControllerTrait.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'InstallController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Progress'.\DIRECTORY_SEPARATOR.'ProgressStorage.php';

        return $container->services['Glpi\\Controller\\InstallController'] = new \Glpi\Controller\InstallController(($container->privates['Glpi\\Progress\\ProgressStorage'] ??= new \Glpi\Progress\ProgressStorage()), ($container->services['logger'] ?? $container->get('logger', 1)));
    }
}
