<?php

namespace Container1XBFHBx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressErrorListenerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the private 'Glpi\Kernel\Listener\ExceptionListener\ProgressErrorListener' shared autowired service.
     *
     * @return \Glpi\Kernel\Listener\ExceptionListener\ProgressErrorListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Kernel'.\DIRECTORY_SEPARATOR.'Listener'.\DIRECTORY_SEPARATOR.'ExceptionListener'.\DIRECTORY_SEPARATOR.'ProgressErrorListener.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Progress'.\DIRECTORY_SEPARATOR.'ProgressStorage.php';

        return $container->privates['Glpi\\Kernel\\Listener\\ExceptionListener\\ProgressErrorListener'] = new \Glpi\Kernel\Listener\ExceptionListener\ProgressErrorListener(($container->privates['Glpi\\Progress\\ProgressStorage'] ??= new \Glpi\Progress\ProgressStorage()));
    }
}
