<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPAxNRhz\Glpi_Kernel_KernelDevelopmentDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPAxNRhz/Glpi_Kernel_KernelDevelopmentDebugContainer.php') {
    touch(__DIR__.'/ContainerPAxNRhz.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelDevelopmentDebugContainer::class, false)) {
    \class_alias(\ContainerPAxNRhz\Glpi_Kernel_KernelDevelopmentDebugContainer::class, Glpi_Kernel_KernelDevelopmentDebugContainer::class, false);
}

return new \ContainerPAxNRhz\Glpi_Kernel_KernelDevelopmentDebugContainer([
    'container.build_hash' => 'PAxNRhz',
    'container.build_id' => 'b1b5eb39',
    'container.build_time' => 1787232095,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPAxNRhz');
