<?php

namespace Container1xQR4xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddTileControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\Config\Helpdesk\AddTileController' shared autowired service.
     *
     * @return \Glpi\Controller\Config\Helpdesk\AddTileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Glpi/DependencyInjection/PublicService.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/Config/Helpdesk/AbstractTileController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/Config/Helpdesk/AddTileController.php';

        return $container->services['Glpi\\Controller\\Config\\Helpdesk\\AddTileController'] = new \Glpi\Controller\Config\Helpdesk\AddTileController();
    }
}
