<?php

namespace Container1xQR4xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomSceneControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\UI\Illustration\CustomSceneController' shared autowired service.
     *
     * @return \Glpi\Controller\UI\Illustration\CustomSceneController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Glpi/DependencyInjection/PublicService.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/UI/Illustration/CustomSceneController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/UI/IllustrationManager.php';

        return $container->services['Glpi\\Controller\\UI\\Illustration\\CustomSceneController'] = new \Glpi\Controller\UI\Illustration\CustomSceneController(($container->privates['Glpi\\UI\\IllustrationManager'] ??= new \Glpi\UI\IllustrationManager()));
    }
}
