<?php

namespace Container1xQR4xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializePluginsService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the private 'Glpi\Kernel\Listener\PostBootListener\InitializePlugins' shared autowired service.
     *
     * @return \Glpi\Kernel\Listener\PostBootListener\InitializePlugins
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Glpi/Kernel/Listener/PostBootListener/InitializePlugins.php';

        return $container->privates['Glpi\\Kernel\\Listener\\PostBootListener\\InitializePlugins'] = new \Glpi\Kernel\Listener\PostBootListener\InitializePlugins(($container->privates['Glpi\\DependencyInjection\\PluginContainer'] ?? self::getPluginContainerService($container)));
    }
}
