<?php

namespace Container1xQR4xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnowbaseItemControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\Knowbase\KnowbaseItemController' shared autowired service.
     *
     * @return \Glpi\Controller\Knowbase\KnowbaseItemController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Glpi/DependencyInjection/PublicService.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/Knowbase/KnowbaseItemController.php';

        return $container->services['Glpi\\Controller\\Knowbase\\KnowbaseItemController'] = new \Glpi\Controller\Knowbase\KnowbaseItemController();
    }
}
