<?php

namespace Container1xQR4xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\Plugin\LogoController' shared autowired service.
     *
     * @return \Glpi\Controller\Plugin\LogoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Glpi/DependencyInjection/PublicService.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/Plugin/LogoController.php';

        return $container->services['Glpi\\Controller\\Plugin\\LogoController'] = new \Glpi\Controller\Plugin\LogoController();
    }
}
