<?php

namespace Container1xQR4xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\ProgressController' shared autowired service.
     *
     * @return \Glpi\Controller\ProgressController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Glpi/DependencyInjection/PublicService.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/ProgressController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Progress/ProgressStorage.php';

        return $container->services['Glpi\\Controller\\ProgressController'] = new \Glpi\Controller\ProgressController(($container->privates['Glpi\\Progress\\ProgressStorage'] ??= new \Glpi\Progress\ProgressStorage()));
    }
}
