<?php

namespace Container1xQR4xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStep3ResolveIssuesControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\Form\Import\Step3ResolveIssuesController' shared autowired service.
     *
     * @return \Glpi\Controller\Form\Import\Step3ResolveIssuesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Glpi/DependencyInjection/PublicService.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/Form/Import/Step3ResolveIssuesController.php';

        return $container->services['Glpi\\Controller\\Form\\Import\\Step3ResolveIssuesController'] = new \Glpi\Controller\Form\Import\Step3ResolveIssuesController();
    }
}
