<?php

namespace Container1xQR4xk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidateAnswerControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\Form\ValidateAnswerController' shared autowired service.
     *
     * @return \Glpi\Controller\Form\ValidateAnswerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/src/Glpi/DependencyInjection/PublicService.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/Form/Utils/CanCheckAccessPolicies.php';
        include_once \dirname(__DIR__, 5).'/src/Glpi/Controller/Form/ValidateAnswerController.php';

        return $container->services['Glpi\\Controller\\Form\\ValidateAnswerController'] = new \Glpi\Controller\Form\ValidateAnswerController();
    }
}
