<?php

namespace Container3XmqeMx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\UI\Illustration\UploadController' shared autowired service.
     *
     * @return \Glpi\Controller\UI\Illustration\UploadController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'PublicService.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'UI'.\DIRECTORY_SEPARATOR.'Illustration'.\DIRECTORY_SEPARATOR.'UploadController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'UI'.\DIRECTORY_SEPARATOR.'IllustrationManager.php';

        return $container->services['Glpi\\Controller\\UI\\Illustration\\UploadController'] = new \Glpi\Controller\UI\Illustration\UploadController(($container->privates['Glpi\\UI\\IllustrationManager'] ??= new \Glpi\UI\IllustrationManager()));
    }
}
