<?php

namespace ContainerOgLt8VI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteFormTranslationControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\Form\Translation\DeleteFormTranslationController' shared autowired service.
     *
     * @return \Glpi\Controller\Form\Translation\DeleteFormTranslationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'PublicService.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'AbstractTranslationController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Translation'.\DIRECTORY_SEPARATOR.'DeleteFormTranslationController.php';

        return $container->services['Glpi\\Controller\\Form\\Translation\\DeleteFormTranslationController'] = new \Glpi\Controller\Form\Translation\DeleteFormTranslationController();
    }
}
