<?php

namespace ContainerOgLt8VI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenericAjaxCrudControllerService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'Glpi\Controller\GenericAjaxCrudController' shared autowired service.
     *
     * @return \Glpi\Controller\GenericAjaxCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'PublicService.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Glpi'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'GenericAjaxCrudController.php';

        return $container->services['Glpi\\Controller\\GenericAjaxCrudController'] = new \Glpi\Controller\GenericAjaxCrudController();
    }
}
